# Generated by Django 4.0.6 on 2022-08-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_product_productcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_quantity_stock',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
