# Generated by Django 4.0.6 on 2022-08-09 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_rename_product_quantity_stock_product_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='product_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProductCategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_cost',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='goods.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
