# Generated by Django 4.0.6 on 2022-08-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
