# Generated by Django 4.0.6 on 2022-08-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_usermodel_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
