# Generated by Django 4.0.6 on 2022-09-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usermodel_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='wallet',
            field=models.FloatField(default=0),
        ),
    ]
