# Generated by Django 4.0.6 on 2022-09-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usermodel_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='wallet',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
